export const provinces = [
    { id: 'an_giang', name: 'An Giang' },
    { id: 'ba_ria_vung_tau', name: 'Bà Rịa - Vũng Tàu' },
    { id: 'bac_giang', name: 'Bắc Giang' },
    { id: 'bac_kan', name: 'Bắc Kạn' },
    { id: 'bac_lieu', name: 'Bạc Liêu' },
    { id: 'bac_ninh', name: 'Bắc Ninh' },
    { id: 'ben_tre', name: 'Bến Tre' },
    { id: 'binh_dinh', name: 'Bình Định' },
    { id: 'binh_duong', name: 'Bình Dương' },
    { id: 'binh_phuoc', name: 'Bình Phước' },
    { id: 'binh_thuan', name: 'Bình Thuận' },
    { id: 'ca_mau', name: 'Cà Mau' },
    { id: 'can_tho', name: 'Cần Thơ' },
    { id: 'cao_bang', name: 'Cao Bằng' },
    { id: 'da_nang', name: 'Đà Nẵng' },
    { id: 'dak_lak', name: 'Đắk Lắk' },
    { id: 'dak_nong', name: 'Đắk Nông' },
    { id: 'dien_bien', name: 'Điện Biên' },
    { id: 'dong_nai', name: 'Đồng Nai' },
    { id: 'dong_thap', name: 'Đồng Tháp' },
    { id: 'gia_lai', name: 'Gia Lai' },
    { id: 'ha_giang', name: 'Hà Giang' },
    { id: 'ha_nam', name: 'Hà Nam' },
    { id: 'ha_noi', name: 'Hà Nội' },
    { id: 'ha_tinh', name: 'Hà Tĩnh' },
    { id: 'hai_duong', name: 'Hải Dương' },
    { id: 'hai_phong', name: 'Hải Phòng' },
    { id: 'hau_giang', name: 'Hậu Giang' },
    { id: 'hoa_binh', name: 'Hòa Bình' },
    { id: 'hung_yen', name: 'Hưng Yên' },
    { id: 'khanh_hoa', name: 'Khánh Hòa' },
    { id: 'kien_giang', name: 'Kiên Giang' },
    { id: 'kon_tum', name: 'Kon Tum' },
    { id: 'lai_chau', name: 'Lai Châu' },
    { id: 'lam_dong', name: 'Lâm Đồng' },
    { id: 'lang_son', name: 'Lạng Sơn' },
    { id: 'lao_cai', name: 'Lào Cai' },
    { id: 'long_an', name: 'Long An' },
    { id: 'nam_dinh', name: 'Nam Định' },
    { id: 'nghe_an', name: 'Nghệ An' },
    { id: 'ninh_binh', name: 'Ninh Bình' },
    { id: 'ninh_thuan', name: 'Ninh Thuận' },
    { id: 'phu_tho', name: 'Phú Thọ' },
    { id: 'phu_yen', name: 'Phú Yên' },
    { id: 'quang_binh', name: 'Quảng Bình' },
    { id: 'quang_nam', name: 'Quảng Nam' },
    { id: 'quang_ngai', name: 'Quảng Ngãi' },
    { id: 'quang_ninh', name: 'Quảng Ninh' },
    { id: 'quang_tri', name: 'Quảng Trị' },
    { id: 'soc_trang', name: 'Sóc Trăng' },
    { id: 'son_la', name: 'Sơn La' },
    { id: 'tay_ninh', name: 'Tây Ninh' },
    { id: 'thai_binh', name: 'Thái Bình' },
    { id: 'thai_nguyen', name: 'Thái Nguyên' },
    { id: 'thanh_hoa', name: 'Thanh Hóa' },
    { id: 'thua_thien_hue', name: 'Thừa Thiên Huế' },
    { id: 'tien_giang', name: 'Tiền Giang' },
    { id: 'tp_ho_chi_minh', name: 'TP. Hồ Chí Minh' },
    { id: 'tra_vinh', name: 'Trà Vinh' },
    { id: 'tuyen_quang', name: 'Tuyên Quang' },
    { id: 'vinh_long', name: 'Vĩnh Long' },
    { id: 'vinh_phuc', name: 'Vĩnh Phúc' },
    { id: 'yen_bai', name: 'Yên Bái' },
];

export const PER_PAGE = 20;
